import os
os.system("pip install Flask")
os.system("pip install requests")
os.system("pip install beautifulsoup4")
os.system("pip install numpy")
os.system("pip install pandas")
os.system("pip install Pillow")
os.system("pip install tensorflow")
os.system("pip install pyyaml")
os.system("pip install torch")
# p2
os.system("pip3 install Flask")
os.system("pip3 install requests")
os.system("pip3 install beautifulsoup4")
os.system("pip3 install numpy")
os.system("pip3 install pandas")
os.system("pip3 install Pillow")
os.system("pip3 install tensorflow")
os.system("pip3 install pyyaml")
os.system("pip3 install torch")